image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: registry.gitlab.com/victor-vargas2009/multi-docker:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-docker:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build:
  stage: build
  script:
  - docker build --pull -t $TEST_IMAGE -f ./client/Dockerfile.dev ./client
  - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE npm test -- --coverage

# after_success:
#  - docker build -t vargasreyesvucsf/muti-client ./client
#  - docker build -t vargasreyesvucsf/muti-nginx ./nginx
#  - docker build -t vargasreyesvucsf/muti-server ./server
#  - docker build -t vargasreyesvucsf/muti-worker ./worker

