image: docker:latest
services:
- docker:dind

stages:
- build_test_client
- test
- build
- release

variables:
  CLIENT_TAG_NAME: vargasreyesvucsf/multi-client
  CLIENT_BUILD_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:$CI_COMMIT_REF_NAME
  NGINX_BUILD_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:$CI_COMMIT_REF_NAME
  SERVER_BUILD_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:$CI_COMMIT_REF_NAME
  WORKER_BUILD_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:$CI_COMMIT_REF_NAME
  # Images used in the release to be tagged as latest
  CLIENT_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:latest
  NGINX_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-nginx:latest
  SERVER_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-server:latest
  WORKER_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-worker:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_test_client:
  stage: build_test_client
  script:
  - docker build --pull -t $CLIENT_BUILD_IMAGE -f ./client/Dockerfile.dev ./client
  - docker run $CLIENT_BUILD_IMAGE npm test -- --coverage

test:
  stage: test
  script:
  - docker pull $CLIENT_BUILD_IMAGE
  - docker run $CLIENT_BUILD_IMAGE npm test -- --coverage

build:
  stage: build
  script:
    - docker build --pull -t $CLIENT_BUILD_IMAGE ./client
    - docker build --pull -t $NGINX_BUILD_IMAGE ./nginx
    - docker build --pull -t $SERVER_BUILD_IMAGE ./server
    - docker build --pull -t $WORKER_BUILD_IMAGE ./worker
    # Pushing Images into Gitlab
    - docker push $CLIENT_BUILD_IMAGE
    - docker push $NGINX_BUILD_IMAGE
    - docker push $SERVER_BUILD_IMAGE
    - docker push $WORKER_BUILD_IMAGE
  only:
    - master
  when: on_success

release:
  stage: release
  script:
    - docker pull $CLIENT_BUILD_IMAGE
    - docker tag $CLIENT_BUILD_IMAGE $CLIENT_RELEASE_IMAGE
    - docker push $CLIENT_RELEASE_IMAGE

    - docker pull $NGINX_BUILD_IMAGE
    - docker tag $NGINX_BUILD_IMAGE $NGINX_RELEASE_IMAGE
    - docker push $NGINX_RELEASE_IMAGE

    - docker pull $SERVER_BUILD_IMAGE
    - docker tag $SERVER_BUILD_IMAGE $SERVER_RELEASE_IMAGE
    - docker push $SERVER_RELEASE_IMAGE

    - docker pull $WORKER_BUILD_IMAGE
    - docker tag $WORKER_BUILD_IMAGE $WORKER_BUILD_IMAGE
    - docker push $WORKER_BUILD_IMAGE
  only:
    - master
  when: on_success