image: docker:latest
services:
- docker:dind

stages:
- build_test
- test
- build_prod
- release

variables:
  CLIENT_TEST_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:$CI_COMMIT_REF_NAME
  CLIENT_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-client:latest
  NGINX_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-nginx:latest
  SERVER_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-server:latest
  WORKER_RELEASE_IMAGE: registry.gitlab.com/victor-vargas2009/multi-worker:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build_test:
  stage: build_test
  script:
  - docker build --pull -t $CLIENT_TEST_IMAGE -f ./client/Dockerfile.dev ./client

test:
  stage: test
  script:
    - docker run $CLIENT_TEST_IMAGE npm test -- --coverage

build_prod:
  stage: cleanup_bbuild_produild
  script:
    - docker build --pull -t $CLIENT_RELEASE_IMAGE ./client
    - docker build --pull -t $NGINX_RELEASE_IMAGE ./nginx
    - docker build --pull -t $SERVER_RELEASE_IMAGE ./server
    - docker build --pull -t $WORKER_RELEASE_IMAGE ./worker
    # Pushing Images into Gitlab
    - docker push $CLIENT_RELEASE_IMAGE
    - docker push $NGINX_RELEASE_IMAGE
    - docker push $SERVER_RELEASE_IMAGE
    - docker push $WORKER_RELEASE_IMAGE
  only:
    - master
  when: on_success
